# Generated by Django 4.2.1 on 2024-07-09 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("appointments", "0002_initial"),
        ("establishments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="establishment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments_establishment",
                to="establishments.establishment",
            ),
        ),
    ]
