# Generated by Django 4.2.1 on 2024-07-09 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("appointments", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments_patients",
                to="patients.patient",
            ),
        ),
    ]
