# Generated by Django 4.2.1 on 2024-07-09 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        ("establishments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorestablishment",
            name="establishment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="associated_establishments",
                to="establishments.establishment",
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="doctors.doctoraddress",
            ),
        ),
    ]
