# Generated by Django 4.2.1 on 2024-07-09 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("feedbacks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_feedbacks",
                to="patients.patient",
            ),
        ),
    ]
